### ISSUE TITLE
Artifact release

### ISSUE THREAD

**Issue by malesch** [luminus-framework/ring-undertow-adapter#1]
I would like to use the undertow adapter in a project.
Is there a release of the artifact to be expected in the near future or are there known limitations which would speak against this? 
Many thanks for your work!

**Comment by yogthos** [comment]
Hi,

It should work fine for the current functionality. I was hoping to add websocket support for the release, but that ended up being a bit of a rabbit hole and I didn't have time to investigate properly. That said, I could publish the current version to Clojars.

**Comment by malesch** [comment]
Perfect, thanks!

**Comment by yogthos** [comment]
and it's up on Clojars :)

**Comment by malesch** [comment]
:+1:
