### ISSUE TITLE
session is not compatible with Ring spec

### ISSUE THREAD

**Issue by yogthos** [luminus-framework/ring-undertow-adapter#13]
Currently, the session is wrapped in a `delay` [here](https://github.com/luminus-framework/ring-undertow-adapter/blob/535f5b6498659a4097aa2419076bae55b366e9f0/src/ring/adapter/undertow/middleware/session.clj#L80), this will cause middleware that operates on the session to error out.

**Comment by nikolap** [comment]
Resolved with 1.1.5
