### ISSUE TITLE
Clojars package has an additional .jar file inside the original .jar file

### ISSUE THREAD

**Issue by harishcm** [luminus-framework/ring-undertow-adapter#19]
Hi, it seems that the Clojars package for `ring-undertow-adapter` has an additional `.jar` file inside the original `.jar` file. 

This additional `.jar` file results in an error when trying to be read/opened, e.g. by `lein nvd check`.

Minimum reproduction below:
![image](https://user-images.githubusercontent.com/159447/130011952-c60975bf-1554-4ecc-84fe-a3da253c7094.png)
Note: `[lein-nvd "1.5.0"]` was added to the `:plugins` vector in `project.clj`.  

<br />

Contents of `ring-undertow-adapter-1.2.1.jar`:
![image](https://user-images.githubusercontent.com/159447/130012645-a8d0e8ce-e52c-4878-91bb-b07192e41392.png)
Note: Additional `.jar` file in `ring-undertow-adapter-1.2.1.jar`

Manually removing the additional `.jar` file allows `lein nvd check` to complete.

Many thanks!

**Comment by nikolap** [comment]
Thanks, resolved with 1.2.3
