### ISSUE TITLE
Java version incompatibility in 1.3.0

### ISSUE THREAD

**Issue by winks** [luminus-framework/ring-undertow-adapter#27]
Hi,
it seems this version is not compatible with Java 8 anymore due to a bumped dependency (cf https://github.com/luminus-framework/conman/issues/78 ).

1.2.8 (and luminus-undertow 0.1.16) still works.

I'm not advocating for keeping backwards compatibility, but I think it would warrant a note in the Changelog.

**Comment by yogthos** [comment]
Thanks, I've updated the changelog to reflect the breaking change.
