### ISSUE TITLE
Keystore parameter not evaluated

### ISSUE THREAD

**Issue by malesch** [luminus-framework/ring-undertow-adapter#3]
SSL support cannot be activated by passing the the existing `:keystore` parameter.

**Comment by yogthos** [comment]
Thanks for the PR, just pushed out 1.0.1 to Clojars with the fix.

**Comment by malesch** [comment]
Whow, impressed, almost in real time! (or is there a bot in operation :wink:).
Thanks a lot!

**Comment by yogthos** [comment]
Oh haha just happened to be at the computer, and no prob. :)
